from StatisticalAnalysis.statisticalAnalysis import statisticalAnalysis

KFoldComparisionPath = "/home/magarcd/Escritorio/ObjectClassificationByTransferLearning/ObjectClassificationByTransferLearning/results/melanoma/kfold-comparison-resnet.csv"
statisticalAnalysis(KFoldComparisionPath)
